[package]
name = "time-of-day"
version = "0.1.0"
authors = ["Magic Len <len@magiclen.org>"]
edition = "2024"
rust-version = "1.85"
repository = "https://github.com/magiclen/time-of-day"
homepage = "https://magiclen.org/time-of-day"
keywords = []
categories = ["date-and-time", "database", "parser-implementations", "value-formatting"]
description = "A time-of-day type supporting the inclusive range from 00:00:00 through 24:00:00."
license = "MIT"
include = ["src/**/*", "Cargo.toml", "README.md", "LICENSE"]

[dependencies]
