[package]
name = "time-of-day"
version = "0.1.3"
authors = ["Magic Len <len@magiclen.org>"]
edition = "2024"
rust-version = "1.88"
repository = "https://github.com/magiclen/time-of-day"
homepage = "https://magiclen.org/time-of-day"
keywords = ["time", "24-00", "database", "midnight", "overnight"]
categories = ["no-std", "date-and-time", "database", "parser-implementations", "value-formatting"]
description = "A time-of-day type supporting the inclusive range from 00:00:00 through 24:00:00."
license = "MIT"
include = ["src/**/*", "Cargo.toml", "README.md", "LICENSE"]

[dependencies]
chrono = { version = "0.4", default-features = false, optional = true }
jiff = { version = "0.2", default-features = false, optional = true }
serde = { version = "1", default-features = false, optional = true }
time = { version = "0.3", default-features = false, optional = true }

[dev-dependencies]
serde_json = "1"

[features]
default = ["std"]

std = []

serde = ["dep:serde"]
chrono = ["dep:chrono"]
time = ["dep:time"]
jiff = ["dep:jiff"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]