[package]
name = "time-of-day-sqlx"
version = "0.1.0"
authors = ["Magic Len <len@magiclen.org>"]
edition = "2024"
rust-version = "1.94"
repository = "https://github.com/magiclen/time-of-day"
homepage = "https://magiclen.org/time-of-day"
keywords = ["time", "sqlx", "database"]
categories = ["date-and-time", "database"]
description = "SQLx integrations for time-of-day."
license = "MIT"
include = ["src/**/*", "Cargo.toml", "README.md", "LICENSE"]

[dependencies]
time-of-day = { version = "0.1", path = "../time-of-day" }

sqlx-core = { version = "0.9", default-features = false }
sqlx-mysql = { version = "0.9", default-features = false, optional = true }
sqlx-postgres = { version = "0.9", default-features = false, optional = true }
sqlx-sqlite = { version = "0.9", default-features = false, features = ["bundled"], optional = true }

[dev-dependencies]
futures-executor = "0.3"

[features]
default = []
postgres = ["dep:sqlx-postgres"]
mysql = ["dep:sqlx-mysql"]
sqlite = ["dep:sqlx-sqlite"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]